### ISSUE TITLE
人员管理中新增人员提示通讯失败！请重试！

### ISSUE THREAD

**Issue by Zynismus16** [phpk/gdoa#1]
运行日志
```
 SQL: INSERT INTO `rt_user` (`username`,`name`,`password`,`salt`,`phone`,`status`,`remark`,`group_id`,`rules`,`users`,`telephone`,`job_number`,`work_place`,`hired_date`) VALUES ('csce','cesdf','525508f99156e23bea28eecfe3863019','RytwFs2my7EbT4WZ','',0,'',1,'','{\"user\":0,\"user_company\":-1,\"user_dept\":-1,\"stock_storehouse\":-1,\"user_store\":-1,\"user_pos\":-1,\"user_role\":-1,\"user_area\":-1,\"project\":-1}','','','',''), Time: 2ms
Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '' for column 'hired_date' at row 1
    at Query.Sequence._packetToError (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/www/wwwroot/GodoOA/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
    at /www/wwwroot/GodoOA/node_modules/.pnpm/think-helper@1.1.4/node_modules/think-helper/index.js:83:10
    at new Promise (<anonymous>)
    at /www/wwwroot/GodoOA/node_modules/.pnpm/think-helper@1.1.4/node_modules/think-helper/index.js:82:12
    at ThinkMysql.[think-mysql-query] (/www/wwwroot/GodoOA/node_modules/.pnpm/think-mysql@1.4.4/node_modules/think-mysql/index.js:169:12)
    at /www/wwwroot/GodoOA/node_modules/.pnpm/think-mysql@1.4.4/node_modules/think-mysql/index.js:247:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sqlMessage: "Incorrect datetime value: '' for column 'hired_date' at row 1",
  sqlState: '22007',
  index: 0,
```

**Comment by phpk** [comment]
已修复。
